import { Municipality } from './app/types';

export const MONTH_CODES: Record<string, string> = {
  '01': 'A',
  '02': 'B',
  '03': 'C',
  '04': 'D',
  '05': 'E',
  '06': 'H',
  '07': 'L',
  '08': 'M',
  '09': 'P',
  '10': 'R',
  '11': 'S',
  '12': 'T',
};

// Values for Check Digit Calculation (Control Character)
export const ODD_VALUES: Record<string, number> = {
  '0': 1,
  '1': 0,
  '2': 5,
  '3': 7,
  '4': 9,
  '5': 13,
  '6': 15,
  '7': 17,
  '8': 19,
  '9': 21,
  A: 1,
  B: 0,
  C: 5,
  D: 7,
  E: 9,
  F: 13,
  G: 15,
  H: 17,
  I: 19,
  J: 21,
  K: 2,
  L: 4,
  M: 18,
  N: 20,
  O: 11,
  P: 3,
  Q: 6,
  R: 8,
  S: 12,
  T: 14,
  U: 16,
  V: 10,
  W: 22,
  X: 25,
  Y: 24,
  Z: 23,
};

export const EVEN_VALUES: Record<string, number> = {
  '0': 0,
  '1': 1,
  '2': 2,
  '3': 3,
  '4': 4,
  '5': 5,
  '6': 6,
  '7': 7,
  '8': 8,
  '9': 9,
  A: 0,
  B: 1,
  C: 2,
  D: 3,
  E: 4,
  F: 5,
  G: 6,
  H: 7,
  I: 8,
  J: 9,
  K: 10,
  L: 11,
  M: 12,
  N: 13,
  O: 14,
  P: 15,
  Q: 16,
  R: 17,
  S: 18,
  T: 19,
  U: 20,
  V: 21,
  W: 22,
  X: 23,
  Y: 24,
  Z: 25,
};

export const REMAINDER_TO_CHAR = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';

// Common Italian Cities for demo purposes
export const POPULAR_MUNICIPALITIES: Municipality[] = [
  { name: 'Roma', code: 'H501' },
  { name: 'Milano', code: 'F205' },
  { name: 'Napoli', code: 'F839' },
  { name: 'Torino', code: 'L219' },
  { name: 'Palermo', code: 'G273' },
  { name: 'Genova', code: 'D969' },
  { name: 'Bologna', code: 'A944' },
  { name: 'Firenze', code: 'D612' },
  { name: 'Bari', code: 'A662' },
  { name: 'Catania', code: 'C351' },
  { name: 'Venezia', code: 'L736' },
  { name: 'Verona', code: 'L781' },
  { name: 'Messina', code: 'F158' },
  { name: 'Padova', code: 'G224' },
  { name: 'Trieste', code: 'L424' },
  { name: 'Taranto', code: 'L049' },
  { name: 'Brescia', code: 'B157' },
  { name: 'Parma', code: 'G337' },
  { name: 'Prato', code: 'G999' },
  { name: 'Modena', code: 'F257' },
  { name: 'Reggio di Calabria', code: 'H224' },
  { name: "Reggio nell'Emilia", code: 'H223' },
  { name: 'Perugia', code: 'G478' },
  { name: 'Ravenna', code: 'H199' },
  { name: 'Livorno', code: 'E625' },
  { name: 'Cagliari', code: 'B354' },
  { name: 'Foggia', code: 'D643' },
  { name: 'Rimini', code: 'H294' },
  { name: 'Salerno', code: 'H703' },
  { name: 'Ferrara', code: 'D548' },
  { name: 'Sassari', code: 'I452' },
  { name: 'Latina', code: 'E472' },
  { name: 'Giugliano in Campania', code: 'E054' },
  { name: 'Monza', code: 'F704' },
  { name: 'Siracusa', code: 'I754' },
  { name: 'Bergamo', code: 'A794' },
  { name: 'Pescara', code: 'G482' },
  { name: 'Trento', code: 'L378' },
  { name: 'Forlì', code: 'D704' },
  { name: 'Vicenza', code: 'L840' },
  { name: 'Terni', code: 'L117' },
  { name: 'Bolzano', code: 'A952' },
  { name: 'Novara', code: 'F952' },
  { name: 'Piacenza', code: 'G535' },
  { name: 'Ancona', code: 'A271' },
  { name: 'Andria', code: 'A285' },
  { name: 'Arezzo', code: 'A390' },
  { name: 'Udine', code: 'L483' },
  { name: 'Cesena', code: 'C573' },
  { name: 'Lecce', code: 'E506' },
  { name: 'ESTERO (Foreign Country)', code: 'Z000' }, // Generic
].sort((a, b) => a.name.localeCompare(b.name));
